---
abstract: 'Automatically Learns Decision Trees'
author:
  - 'Ken Williams <kwilliams@cpan.org>'
build_requires:
  English: 0
  Test: 0
  Test::More: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300009, CPAN::Meta::Converter version 2.120351'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AI-DecisionTree
requires:
  Carp: 0
  GraphViz: 0
  strict: 0
  vars: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=AI-DecisionTree
  repository: git://github.com/kenahoo/perl-ai-decisiontree.git
version: 0.11
